AWSTemplateFormatVersion: 2010-09-09
Description: techco-serverless
Transform: AWS::Serverless-2016-10-31
Resources:
  phpserver:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${AWS::StackName}-phpserver
      Description: PHP Webserver
      CodeUri: s3://techco-serverless/b5ec93fa9b8ae974557cbf0666135af2
      Runtime: provided
      Handler: router.php
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Layers:
      - Fn::Sub: arn:aws:lambda:${AWS::Region}:887080169480:layer:php71:4
      VpcConfig:
        SecurityGroupIds:
        - sg-08a525c9a44cb7c09
        SubnetIds:
        - subnet-06a6f9e1c5384cf64
      Events:
        api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
