AWSTemplateFormatVersion: 2010-09-09
Description: techco-wp
Transform: AWS::Serverless-2016-10-31
Resources:
  phpserver:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${AWS::StackName}-phpserver
      Description: PHP Webserver
      CodeUri: s3://techco-lambda-wp/c2f90e25de18d49f9237819d00c566cd
      Runtime: provided
      Handler: router.php
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Layers:
      - Fn::Sub: arn:aws:lambda:${AWS::Region}:887080169480:layer:php71:4
      VpcConfig:
        SecurityGroupIds:
        - sg-d0a5c3a8
        SubnetIds:
        - subnet-c42f2e8d
      Events:
        api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
